import React, { useState } from "react";

export default function ExportBar({ result, mode }) {
  const [copied, setCopied] = useState(false);
  const [exportError, setExportError] = useState("");

  if (!result || mode !== "productive") return null;

  const formatDebateText = () => {
    return `# Debate Analysis - Productive Mode

**Participants:**
- ${result.person1Name}: ${result.person1Argument}
- ${result.person2Name}: ${result.person2Argument}

**Winner:** ${result.winner}
**Scores:** ${result.person1Name} (${result.winner === result.person1Name ? result.winnerScore : result.loserScore}/10) vs ${result.person2Name} (${result.winner === result.person2Name ? result.winnerScore : result.loserScore}/10)

**Analysis:**
${result.analysis}

---
Generated by Debate Mate (debate-mate.app)`;
  };

  const handleCopyToClipboard = async (text) => {
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      setExportError("Failed to copy to clipboard");
      setTimeout(() => setExportError(""), 3000);
    }
  };

  const handleNotes = async () => {
    const text = formatDebateText();
    if (navigator.share) {
      try {
        await navigator.share({
          title: "Debate Analysis",
          text: text,
        });
      } catch (err) {
        if (err.name !== "AbortError") {
          // Fallback to clipboard
          handleCopyToClipboard(text);
        }
      }
    } else {
      handleCopyToClipboard(text);
    }
  };

  const handleEvernote = () => {
    const text = formatDebateText();
    const title = encodeURIComponent(`Debate: ${result.person1Name} vs ${result.person2Name}`);
    const content = encodeURIComponent(text);
    
    // Try Evernote deep link
    const evernoteUrl = `evernote://new?title=${title}&body=${content}`;
    
    // Try to open Evernote, fallback to clipboard if it fails
    const link = document.createElement("a");
    link.href = evernoteUrl;
    link.style.display = "none";
    document.body.appendChild(link);
    
    setTimeout(() => {
      document.body.removeChild(link);
      // If Evernote didn't open, copy to clipboard
      handleCopyToClipboard(text);
    }, 500);
  };

  const handleNotion = () => {
    const text = formatDebateText();
    
    // Notion doesn't have a reliable deep link, so we copy formatted text
    // User can paste into Notion
    handleCopyToClipboard(text);
    
    // Try notion:// protocol (may not work on all systems)
    try {
      const notionUrl = `notion://www.notion.so/new?title=${encodeURIComponent(`Debate: ${result.person1Name} vs ${result.person2Name}`)}`;
      window.open(notionUrl, "_blank");
    } catch (err) {
      // Ignore if it fails, clipboard copy already happened
    }
  };

  const handleSaveLocal = () => {
    const text = formatDebateText();
    const blob = new Blob([text], { type: "text/plain;charset=utf-8" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `debate-${result.person1Name}-vs-${result.person2Name}-${Date.now()}.txt`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="mt-4 rounded-xl border border-white/10 bg-white/5 p-4">
      <div className="flex flex-wrap items-center gap-3">
        <button
          onClick={handleNotes}
          className="flex items-center gap-2 rounded-lg border border-white/10 bg-white/5 px-4 py-2 text-sm font-semibold text-white hover:bg-white/10 transition"
          title="Send to Notes"
        >
          📝 Notes
        </button>

        <button
          onClick={handleEvernote}
          className="flex items-center gap-2 rounded-lg border border-white/10 bg-white/5 px-4 py-2 text-sm font-semibold text-white hover:bg-white/10 transition"
          title="Export to Evernote"
        >
          🟢 Evernote
        </button>

        <button
          onClick={handleNotion}
          className="flex items-center gap-2 rounded-lg border border-white/10 bg-white/5 px-4 py-2 text-sm font-semibold text-white hover:bg-white/10 transition"
          title="Copy for Notion"
        >
          {copied ? "✓ Copied!" : "🎯 Notion"}
        </button>

        <button
          onClick={handleSaveLocal}
          className="flex items-center gap-2 rounded-lg border border-white/10 bg-white/5 px-4 py-2 text-sm font-semibold text-white hover:bg-white/10 transition"
          title="Download as .txt"
        >
          💾 Save Local
        </button>
      </div>
      {exportError && (
        <p className="mt-2 text-xs text-red-400">{exportError}</p>
      )}
      {copied && !exportError && (
        <p className="mt-2 text-xs text-green-400">Copied to clipboard!</p>
      )}
    </div>
  );
}

